version: '2.4'
services:
  registration_service:
    build:
      context: ./registration
      dockerfile: ./registration/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./registration:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  login_service:
    build:
      context: ./login
      dockerfile: ./login/Dockerfile 
    ports:
      - 8001:8001
    volumes:
      - ./login:/app
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db

  datapredict_service:
    build:
      context: ./datapredict
      dockerfile: Dockerfile  # Updated path to Dockerfile
    ports:
      - 8003:8003
    volumes:
      - ./datapredict:/app
    command: python manage.py runserver 0.0.0.0:8003
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=energy_usage_db

  datapull_service:
    build:
      context: ./datapull
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./datapull:/app
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=energy_usage_db

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: 2020
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33068:3306

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodbdata:/data/db












# version: '2.4'
# services:
#   registration_service:
#     build:
#       context: ./registration
#       dockerfile: ./registration/Dockerfile  # Corrected path to Dockerfile
#     ports:
#       - 8000:8000
#     volumes:
#       - ./registration:/app
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - db


#   login_service:
#     build:
#       context: ./login
#       dockerfile: ./login/Dockerfile  # Corrected path to Dockerfile
#     ports:
#       - 8001:8001
#     volumes:
#       - ./login:/app
#     command: python manage.py runserver 0.0.0.0:8001
#     depends_on:
#       - db

#   datapull_service:
#     build:
#       context: ./datapull
#       dockerfile: Dockerfile
#     ports:
#       - 8002:8002
#     volumes:
#       - ./datapull:/app
#     command: python manage.py runserver 0.0.0.0:8002
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_HOST=mongodb
#       - MONGO_PORT=27017
#       - MONGO_DB_NAME=energy_usage_db
#   db:
#     image: mysql:8.0.33
#     restart: always
#     environment:
#       MYSQL_DATABASE: admin
#       MYSQL_ROOT_PASSWORD: 2020
#     volumes:
#       - .dbdata:/var/lib/mysql
#     ports:
#       - 33068:3306

#   mongodb:
#     image: mongo:latest
#     restart: always
#     ports:
#       - 27017:27017
#     volumes:
#       - ./mongodbdata:/data/db
